### ISSUE TITLE
deletedirectory api is not working properly? 

### ISSUE THREAD

**Issue by kumaresan-subramani** [itsananderson/kudu-api#30] opened 2020-03-17 05:29 UTC
## ref:
https://github.com/itsananderson/kudu-api#virtual-file-system-kuduvfs

## description
I have tried below to delete my directory in azure, but api call get executed properly but directorynot get deleted in azure portal.

## Code snippets:

```
var kuduApi = require("kudu-api");

var api = kuduApi(settings.kudu);

api.vfs.deleteDirectory("site/beta/check/", function (err) {
                    if (err) {
                        console.log(err);
                        done();
                    }
                    else {
                        console.log('Delete complete');
                        done();
                    }
});
```

## anything Else:

Upload. download and create directory api working fine

```
api.vfs.createDirectory(backupPath, function (err) {
    if (err) throw err;
});
if (!fs.existsSync('./backUp/')) {
    shelljs.mkdir('-p', 'backUp');
}
api.zip.download("site/beta/check/", "backUp/path.zip", function (err) {
    if (err) {
        console.log(err);
        done();
    }
    else {
        console.log('Download complete');
        api.zip.upload('./backUp/path.zip', backupPath, function (err) {
            if (err) {
                console.log(err);
            }
            else {
                console.log('Upload complete');
            }
        });
        done();
    }
});
```

## Note:

it is working fine for normal directory but when i map some directory in config that wont getdeleted

**Comment by itsananderson** [comment] 2021-04-07 06:53
@kumaresan-subramani can you explain more about how you're mapping a directory in a config? That sounds like it might be related to the issue, but I don't know how to set that up to reproduce the issue.

**Comment by kumaresan-subramani** [comment] 2021-04-07 06:55
HI @itsananderson ,
 
thanks for your reply

i found workaround and resolved year ago

Anyway thanks for fast reply

**Comment by itsananderson** [comment] 2021-04-07 07:01
Ok. I don't actively use this library anymore, so it doesn't get a lot of attention except when I occasionally get some free time. If I can't reproduce this issue I'll go ahead and close it.

**Closed by itsananderson** 2021-04-07 07:01 UTC
